### ISSUE TITLE
wrong syntax for np.atleast_1d ?

### ISSUE THREAD

**Issue by edstevenson** [discsim/frank#210] opened 2023-09-28 11:38 UTC
line 426 of utilities.py

`np.atleast_1d(wle, dtype='f8')` raises TypeError

should maybe be `np.atleast_1d(wle).astype('f8')` ?

**Comment by rbooth200** [comment] 2023-09-28 12:25
Can you provide a minimum example that reproduces the error?

**Comment by jeffjennings** [comment] 2023-10-26 18:38
This is due to an update to the numpy core; the `dtype` arg is no longer accepted by `np.atleast_1d` as of some recent version (my version of numpy, 1.21.5, returns the error). 

I've fixed in #212 and confirmed the `dtype` arg to `atleast_<x>d' isn't elsewhere in frank.

Thanks @edstevenson!

**Closed** 2023-10-26 19:10 UTC
Labels: bug
